# -*- coding: utf-8 -*-
"""Main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1My11ulLrySForqRb9g-_quA4QrcuEHlX
"""

!git clone https://github.com/NLP-UET/Language-Model.git

!python /content/Language-Model/Main.ipynb

!pip install pyvi

!python ./Language-Model/fastText.py

!python ./Language-Model/make_data.py

!python ./Language-Model/svd.py

!python ./Language-Model/word2vec.py

!python ./Language-Model/using_model_demo.py

!python ./Language-Model/visualize.py